---
- yum: name={{item}} state=present
  with_items:
    - httpd
    - php
    - mariadb-server
- service: name=httpd enabled=yes state=started
- service: name=mariadb-server enabled=yes state=started
- firewalld:
    service: http
    permanent: true
    state: enabled
- service: name=firewalld state=restarted
