---
- yum: name={{item}} state=present
  with_items:
    - firewalld
    - vim-enhanced
    - elinks
    - ntp
    - git
    - wget
    - unzip
    - psmisc
    - libsemanage-python
- service: name=ntpd state=started enabled=yes
- name: Update the /etc/ssh/sshd_config file
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^UseDNS"
    line: "UseDNS no"
    insertafter: EOF
    state: present
  register: ssh_config
- name: Restart ssh
  service:
    name: sshd
    state: restarted
  when: ssh_config.changed
- yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
